"use client";
import { createContext, useContext, useState } from "react";

export type Lang = "ES" | "EN";

const ES = {
  // ── Layout / Nav ────────────────────────────────────────────
  expandMenu: "Expandir menú",
  collapseMenu: "Colapsar menú",
  mainMenu: "MENÚ PRINCIPAL",
  system: "SISTEMA",
  logout: "Cerrar sesión",
  searchPH: "Buscar...",
  notifications: "Notificaciones",
  clearAll: "Limpiar todo",
  noNotifications: "No hay notificaciones",
  changePassword: "Cambiar clave",
  navDashboard: "Dashboard",
  navClientes: "Clientes",
  navPedidos: "Pedidos",
  navMensajes: "Mensajes",
  navProyectos: "Proyectos Concluidos",
  navCancelados: "Proyectos Cancelados",
  navFechaEntrega: "Fecha de Entrega",
  navFechaInicio: "Fecha de Inicio",
  navAlertas: "Alertas",
  navPagos: "Pagos",
  navConfiguracion: "Configuración",
  navReporte: "Reporte Técnico",
  timeNow: "ahora",
  timeMinAgo: (m: number) => `hace ${m} min`,
  timeHAgo: (h: number) => `hace ${h}h`,
  timeDayAgo: (d: number) => `hace ${d}d`,

  // ── Dashboard ───────────────────────────────────────────────
  dashTitle: "Dashboard",
  dashSubtitle: "Bienvenido de vuelta, Admin",
  dashEnDesarrollo: "En desarrollo",
  dashCancelados: "Cancelados",
  dashShortcuts: "Accesos rápidos",
  dashPedidosMes: "Pedidos por mes",
  dashPedidosEstado: "Pedidos por estado",
  dashPedidosActivos: "Pedidos Activos",
  dashNoPedidosActivos: "No hay pedidos activos",
  dashPedidosPlazo: "Pedidos con Plazo Máximo",
  dashNoPedidosPlazo: "No hay pedidos con plazo registrado",
  dashProyecto: "Proyecto",
  dashCliente: "Cliente",
  dashEstado: "Estado",
  dashPlazo: "Plazo",
  dashVencido: "Vencido",
  dashHoy: "Hoy",
  dashPendiente: "Pendiente",
  dashDesarrollo: "En desarrollo",
  dashRevision: "En revisión",
  dashEntregado: "Entregado",

  // ── Clientes ────────────────────────────────────────────────
  clientesTitle: "Clientes",
  clientesSubtitle: "Registro de nuevo cliente",
  clientesConfirmTitle: "¿Guardar cliente?",
  clientesConfirmMsg: "Se registrará el nuevo cliente en el sistema. ¿Deseas continuar?",
  clientesConfirmBtn: "Sí, guardar",
  clientesDatosPersonales: "DATOS PERSONALES",
  clientesNombreCompleto: "Nombre completo",
  clientesDni: "DNI / Cédula",
  clientesCorreo: "Correo electrónico",
  clientesTelefono: "Número de teléfono",
  clientesPais: "País",
  clientesSelPais: "Seleccionar país",
  clientesAppWeb: "Nombre de la App / Web",
  clientesFechasContrato: "FECHAS Y CONTRATO",
  clientesFechaInicio: "Fecha de inicio",
  clientesSelFechaInicio: "Seleccionar fecha de inicio",
  clientesFechaMaxima: "Fecha máxima de entrega",
  clientesSelFechaMaxima: "Seleccionar fecha máxima",
  clientesDuracion: "Duración del contrato",
  clientesSelDuracion: "Seleccionar duración",
  clientesSinContrato: "Sin contrato",
  clientesTipoPago: "Tipo de pago",
  clientesSelTipoPago: "Seleccionar tipo de pago",
  clientesPagoMensual: "Pagos mensuales",
  clientesPagoUnico: "Un solo pago",
  clientesValorMensual: "Valor mensual (USD)",
  clientesValorTotal: "Valor total (USD)",
  clientesAcceso: "ACCESO AL SISTEMA",
  clientesPassword: "Contraseña",
  clientesCrearPasswordPH: "Crear contraseña",
  clientesConfirmarPassword: "Confirmar contraseña",
  clientesRepetirPasswordPH: "Repetir contraseña",
  clientesPasswordNoCoinciden: "Las contraseñas no coinciden",
  clientesGuardar: "Guardar cliente",
  clientesRegistrados: "Clientes registrados",
  clientesBuscar: "Buscar por nombre, correo, país...",
  clientesContrato: "Contrato",
  clientesValor: "Valor",
  clientesInicio: "Inicio",
  clientesCargando: "Cargando...",
  clientesSinResultados: "Sin resultados",
  clientesEjNombre: "Ej. Carlos Méndez",
  clientesEjDni: "Ej. 12345678",
  clientesEjTelefono: "+51 999 999 999",
  clientesEjAppWeb: "Ej. MiTienda Online",
  clientesEjValorMensual: "Ej. 150.00",
  clientesEjValorTotal: "Ej. 1200.00",
  clientesCampoObligatorio: "Campo obligatorio",
  clientesSelPaisError: "Selecciona un país",
  clientesSelFechaError: "Selecciona una fecha",
  clientesSelDuracionError: "Selecciona la duración",
  clientesSelPagoError: "Selecciona el tipo de pago",
  clientesCrearPasswordError: "Crea una contraseña",
  clientesGuardadoOk: "Cliente guardado correctamente",
  clientesGuardadoError: "Error al guardar el cliente",
  clientesMes: "mes",
  clientesMeses: "meses",
  clientesXMes: "/mes",
  clientesSingular: "cliente",
  clientesPlural: "clientes",

  // ── Pedidos ─────────────────────────────────────────────────
  pedidosTitle: "Pedidos",
  pedidosSubtitleNuevo: "Registro de nuevo pedido",
  pedidosSubtitleEditar: "Editando pedido existente",
  pedidosCancelarEdicion: "Cancelar edición",
  pedidosConfirmTitleNuevo: "¿Guardar pedido?",
  pedidosConfirmTitleEditar: "¿Guardar cambios?",
  pedidosConfirmMsgNuevo: "Se registrará el nuevo pedido en el sistema. ¿Deseas continuar?",
  pedidosConfirmMsgEditar: "Se actualizarán los datos del pedido. ¿Deseas continuar?",
  pedidosConfirmBtn: "Sí, guardar",
  pedidosDatos: "DATOS DEL PEDIDO",
  pedidosCliente: "Cliente",
  pedidosSelCliente: "Seleccionar cliente",
  pedidosNombreProyecto: "Nombre del proyecto",
  pedidosEjProyecto: "Ej. MiTienda Online",
  pedidosTipoProyecto: "Tipo de proyecto",
  pedidosSelTipo: "Seleccionar tipo",
  pedidosTipoServicio: "Tipo de servicio",
  pedidosSelServicio: "Seleccionar servicio",
  pedidosPrioridad: "Prioridad",
  pedidosSelPrioridad: "Seleccionar prioridad",
  pedidosEstadoLabel: "Estado del pedido",
  pedidosSelEstado: "Seleccionar estado",
  pedidosFechaInicio: "Fecha de inicio",
  pedidosSelFechaInicio: "Seleccionar fecha de inicio",
  pedidosFechaEntrega: "Fecha de entrega",
  pedidosSelFechaEntrega: "Seleccionar fecha de entrega",
  pedidosPlataformas: "PLATAFORMAS / TECNOLOGÍAS",
  pedidosSelTecnologias: "Selecciona las tecnologías del proyecto",
  pedidosMensajeInicio: "MENSAJE DE INICIO",
  pedidosMensajeLabel: "Mensaje inicial del proyecto",
  pedidosMensajePH: "Ej. Hola Carlos, comenzamos hoy con el desarrollo de tu proyecto...",
  pedidosGuardar: "Guardar pedido",
  pedidosGuardarCambios: "Guardar cambios",
  pedidosCancelar: "Cancelar",
  pedidosRegistrados: "Pedidos registrados",
  pedidosBuscar: "Buscar por proyecto, cliente...",
  pedidosServicio: "Servicio",
  pedidosEntrega: "Entrega",
  pedidosSinResultados: "Sin resultados",
  pedidosActualizadoOk: "Pedido actualizado correctamente",
  pedidosGuardadoOk: "Pedido guardado correctamente",
  pedidosGuardadoError: "Error al guardar el pedido",
  pedidosSelClienteError: "Selecciona un cliente",
  pedidosNombreError: "Escribe el nombre del proyecto",
  pedidosTipoError: "Selecciona el tipo de proyecto",
  pedidosServicioError: "Selecciona el tipo de servicio",
  pedidosPrioridadError: "Selecciona la prioridad",
  pedidosEstadoError: "Selecciona el estado",
  pedidosFechaInicioError: "Indica la fecha de inicio",
  pedidosFechaEntregaError: "Indica la fecha de entrega",
  pedidosMensajeError: "Escribe un mensaje de inicio",
  pedidosCargando: "Cargando...",
  pedidosSingular: "pedido",
  pedidosPlural: "pedidos",
  pedidosPagoInfo: "INFORMACIÓN DE PAGO",
  pedidosMontoTotal: "Monto total del proyecto (USD)",
  pedidosMontoTotalPH: "Ej. 1200.00",
  pedidosMontoPagado: "Monto pagado (USD)",
  pedidosMontoPagadoPH: "Ej. 600.00",
  pedidosMontoPendiente: "Monto pendiente",
  pedidosSubirComprobante: "Subir comprobante (imagen o PDF)",
  pedidosComprobanteActual: "Comprobante actual",
  pedidosVerComprobante: "Ver comprobante",
  pedidosComprobanteSubiendo: "Subiendo...",
  pedidosComprobanteError: "Error al subir el comprobante",
  pedidosComprobanteOk: "Comprobante subido correctamente",
  tipoWeb: "Sitio / Aplicación Web",
  tipoApp: "Aplicación Móvil (App)",
  tipoDesktop: "Programa de Escritorio",
  prioBaja: "Baja",
  prioMedia: "Media",
  prioAlta: "Alta",
  prioUrgente: "Urgente",
  estadoPendiente: "Pendiente",
  estadoDesarrollo: "En desarrollo",
  estadoRevision: "En revisión",
  estadoEntregado: "Entregado",
  estadoCancelado: "Cancelado",
  badgeWeb: "Web",
  badgeApp: "App Móvil",
  badgeDesktop: "Escritorio",
  srvLanding: "Landing Page",
  srvEcommerce: "E-Commerce / Tienda Online",
  srvAuth: "Sistema de Autenticación",
  srvApi: "API REST / Backend",
  srvDashboard: "Dashboard / Panel Admin",
  srvBlog: "Blog / Portal de Noticias",
  srvPortfolio: "Portafolio / Brochure",
  srvCrm: "CRM / Gestión de Clientes",
  srvErp: "ERP / Gestión Empresarial",
  srvPos: "Punto de Venta (POS)",
  srvBooking: "Reservas / Citas Online",
  srvChat: "Chat / Mensajería en Tiempo Real",
  srvStreaming: "Streaming / Video On Demand",
  srvMarketplace: "Marketplace",
  srvSaas: "SaaS / Software como Servicio",
  srvSocial: "Red Social / Comunidad",
  srvMaps: "Mapas / Geolocalización",
  srvNotif: "Notificaciones Push",
  srvPayments: "Pasarela de Pagos",
  srvIa: "Integración con IA / Chatbot",
  srvScraping: "Web Scraping / Automatización",
  srvOther: "Otro / Personalizado",

  // ── Pagos ────────────────────────────────────────────────────
  pagosTitle: "Pagos",
  pagosSubtitle: "Registro de pagos por pedido",
  pagosCargando: "Cargando pagos...",
  pagosNinguno: "No hay pedidos registrados",
  pagosMontoTotal: "Total",
  pagosMontoPagado: "Pagado",
  pagosMontoPendiente: "Pendiente",
  pagosComprobante: "Comprobante",
  pagosVerComprobante: "Ver",
  pagosSinComprobante: "—",
  pagosResumenFacturado: "Total facturado",
  pagosResumenPagado: "Total pagado",
  pagosResumenPendiente: "Total pendiente",
  pagosResumenPedidos: "Pedidos con pago",
  pagosSaldado: "Saldado",
  pagosDeuda: "Con deuda",
  pagosSinInfo: "Sin info",
  pagosEstadoPago: "Estado pago",
  pagosBuscar: "Buscar por proyecto, cliente...",
  pagosSingular: "pedido",
  pagosPlural: "pedidos",

  // ── Mensajes ────────────────────────────────────────────────
  mensajesTitle: "Mensajes",
  mensajesBuscar: "Buscar cliente...",
  mensajesSinResultados: "Sin resultados",
  mensajesNoHay: "No hay clientes",
  mensajesSinMensajes: "Sin mensajes",
  mensajesSelecciona: "Selecciona un cliente para ver la conversación",
  mensajesVacio: "No hay mensajes todavía. ¡Escribe el primero!",
  mensajesEscribe: "Escribe un mensaje...",
  mensajesExpandir: "Expandir",
  mensajesColapsar: "Colapsar",

  // ── Proyectos Concluidos ─────────────────────────────────────
  proyectosTitle: "Proyectos Concluidos",
  proyectosNinguno: "No hay proyectos concluidos todavía",
  proyectosCargando: "Cargando proyectos concluidos...",
  proyectosSingular: "proyecto",
  proyectosPlural: "proyectos",
  proyectosTermSingular: "terminado",
  proyectosTermPlural: "terminados",
  proyectosMensajeFinalLabel: "Mensaje final para el cliente",
  proyectosGuardarMensaje: "Guardar mensaje",
  proyectosCerrar: "Cerrar",
  proyectosEditarMensaje: "Editar mensaje",
  proyectosMensajeFinalBtn: "Mensaje final",
  proyectosGuardadoOk: "Mensaje guardado correctamente",
  proyectosGuardadoError: "Error al guardar el mensaje",

  // ── Proyectos Cancelados ─────────────────────────────────────
  canceladosTitle: "Proyectos Cancelados",
  canceladosNinguno: "No hay proyectos cancelados",
  canceladosCargando: "Cargando proyectos cancelados...",
  canceladosSingular: "proyecto",
  canceladosPlural: "proyectos",
  canceladosCancelSingular: "cancelado",
  canceladosCancelPlural: "cancelados",
  canceladosMotivoLabel: "Motivo de cancelación",
  canceladosMotivoPH: "Describe el motivo por el que se canceló el proyecto...",
  canceladosGuardarMotivo: "Guardar motivo",
  canceladosCerrar: "Cerrar",
  canceladosEditarMotivo: "Editar motivo",
  canceladosMotivoBtn: "Motivo",
  canceladosGuardadoOk: "Motivo guardado correctamente",
  canceladosGuardadoError: "Error al guardar el motivo",
  canceladosInicioLabel: "Inicio",
  canceladosCanceladoLabel: "Cancelado",

  // ── Fecha Entrega ────────────────────────────────────────────
  fechaEntregaTitle: "Fechas de Entrega",
  fechaEntregaSubtitle: "Proyectos ordenados por plazo máximo",
  fechaEntregaCargando: "Cargando fechas de entrega...",
  fechaEntregaNoPedidos: "No hay pedidos registrados",
  fechaEntregaVencidoHace: "Vencido hace",
  fechaEntregaVenceHoy: "Vence hoy",
  fechaEntregaEntregado: "Entregado",
  fechaEntregaVencidosSing: "vencido",
  fechaEntregaVencidosPlu: "vencidos",
  fechaEntregaUrgentesSing: "urgente",
  fechaEntregaUrgentesPlu: "urgentes",
  fechaEntregaTresDias: "(≤ 3 días)",
  fechaEntregaEntregadosSing: "entregado",
  fechaEntregaEntregadosPlu: "entregados",
  diaSingular: "día",
  diasPlural: "días",

  // ── Fecha Inicio ─────────────────────────────────────────────
  fechaInicioTitle: "Fechas de Inicio",
  fechaInicioSubtitle: "Historial de proyectos por fecha de arranque",
  fechaInicioCargando: "Cargando fechas de inicio...",
  fechaInicioNoPedidos: "No hay pedidos registrados",

  // ── Alertas ──────────────────────────────────────────────────
  alertasTitle: "Alertas",
  alertasTodoOk: "Todo en orden — sin alertas activas",
  alertasCargando: "Analizando alertas...",
  alertasSinPendientes: "Sin pendientes",
  alertasVencidas: "Entregas vencidas",
  alertasHoy: "Vencen hoy",
  alertasProximas: "Entregas próximas (≤ 7 días)",
  alertasUrgentes: "Pedidos urgentes en curso",
  alertasPendientes: "Pedidos pendientes de inicio",
  alertasCancelados: "Proyectos cancelados",
  alertasVencioEl: "Venció el",
  alertasEstadoLabel: "Estado",
  alertasEnDias: (d: number) => `En ${d} día${d !== 1 ? "s" : ""}`,
  alertasPrioridadLabel: "Prioridad",
  alertasCanceladoEl: "Cancelado el",
  alertasSingular: "alerta",
  alertasPlural: "alertas",
  alertasActivaSingular: "activa",
  alertasActivaPlural: "activas",

  // ── Configuración ────────────────────────────────────────────
  configTitle: "Configuración",
  configSubtitle: "Ajustes del administrador y del sistema",
  configCargando: "Cargando configuración...",
  configCambiarFoto: "Cambiar foto",
  configPerfil: "PERFIL DEL ADMINISTRADOR",
  configNombre: "Nombre",
  configNombrePH: "Nombre del admin",
  configCorreo: "Correo electrónico",
  configTelefono: "Teléfono",
  configEmpresa: "DATOS DE LA EMPRESA",
  configNombreEmpresa: "Nombre de la empresa",
  configNombreEmpresaPH: "Mi Empresa",
  configSitio: "Sitio web",
  configSitioPH: "tuempresa.com",
  configCV: "CURRICULUM VITAE",
  configDescargar: "Descargar",
  configSubirCV: "Subir CV (PDF, DOC)",
  configSubiendo: "Subiendo...",
  configImagenError: "La imagen no debe superar 500 KB",
  configArchivoError: "El archivo no debe superar 10 MB",
  configCVSubidoOk: "CV subido correctamente",
  configCVSubidoError: "Error al subir el CV",
  configCVEliminadoOk: "CV eliminado",
  configCVEliminadoError: "Error al eliminar el CV",
  configGuardadoOk: "Configuración guardada correctamente",
  configGuardadoError: "Error al guardar",
  configGuardar: "Guardar configuración",
  configGuardando: "Guardando...",

  // ── Reporte Técnico ──────────────────────────────────────────
  reporteTitle: "Reporte Técnico",
  reporteSubtitle: "Resumen general del sistema",
  reporteExportar: "Exportar / Imprimir",
  reporteTotalClientes: "Total clientes",
  reporteTotalPedidos: "Total pedidos",
  reporteConcluidos: "Proyectos concluidos",
  reporteCancelados: "Proyectos cancelados",
  reporteEnDesarrollo: "En desarrollo / revisión",
  reporteIngresos: "Ingresos estimados",
  reporteResumen: "Resumen",
  reportePedidos: "Pedidos",
  reporteClientes: "Clientes",
  reporteGenerando: "Generando reporte...",
  reporteNoPedidos: "No hay pedidos registrados",
  reporteNoClientes: "No hay clientes registrados",
  reporteProyecto: "Proyecto",
  reporteServicio: "Servicio",
  reporteInicio: "Inicio",
  reporteEntrega: "Entrega",
  reporteEstado: "Estado",
  reportePrioridad: "Prioridad",
  reporteTipo: "Tipo",
  reporteTecnologias: "Tecnologías",
  reporteCorreo: "Correo",
  reportePais: "País",
  reporteContrato: "Contrato",
  reportePago: "Pago",
  reporteValor: "Valor",
  reporteMes: "mes",
  reporteMeses: "meses",
  reporteMensual: "Mensual",
  reporteUnico: "Único",
  reporteConcluidosSeccion: "Proyectos Concluidos —",
  reporteNoProyectosConcluidos: "No hay proyectos concluidos",
  reporteMensajeFinal: "Mensaje final",
  reporteSinMensaje: "Sin mensaje",

  // ── ChangePasswordModal ──────────────────────────────────────
  pwTitle: "Cambiar contraseña",
  pwSubtitle: "Ingresa tu contraseña actual y la nueva",
  pwActual: "Contraseña actual",
  pwActualPH: "Tu contraseña actual",
  pwNueva: "Nueva contraseña",
  pwNuevaPH: "Nueva contraseña",
  pwConfirmar: "Confirmar nueva contraseña",
  pwConfirmarPH: "Repetir nueva contraseña",
  pwNoCoinciden: "Las contraseñas no coinciden",
  pwCancelar: "Cancelar",
  pwCambiar: "Cambiar contraseña",
  pwGuardando: "Guardando...",
  pwErrorActualReq: "Ingresa tu contraseña actual.",
  pwErrorMinChars: "La nueva contraseña debe tener al menos 6 caracteres.",
  pwErrorNoCoinciden: "Las contraseñas nuevas no coinciden.",
  pwErrorActualWrong: "La contraseña actual es incorrecta.",
  pwErrorGeneral: "Ocurrió un error. Intenta de nuevo.",
  pwActualizadaOk: "Contraseña actualizada correctamente",

  // ── Shared ───────────────────────────────────────────────────
  loading: "Cargando...",
  saving: "Guardando...",
  noResults: "Sin resultados",
};

const EN: typeof ES = {
  expandMenu: "Expand menu",
  collapseMenu: "Collapse menu",
  mainMenu: "MAIN MENU",
  system: "SYSTEM",
  logout: "Log out",
  searchPH: "Search...",
  notifications: "Notifications",
  clearAll: "Clear all",
  noNotifications: "No notifications",
  changePassword: "Change password",
  navDashboard: "Dashboard",
  navClientes: "Clients",
  navPedidos: "Orders",
  navMensajes: "Messages",
  navProyectos: "Completed Projects",
  navCancelados: "Cancelled Projects",
  navFechaEntrega: "Delivery Date",
  navFechaInicio: "Start Date",
  navAlertas: "Alerts",
  navPagos: "Payments",
  navConfiguracion: "Settings",
  navReporte: "Technical Report",
  timeNow: "just now",
  timeMinAgo: (m: number) => `${m} min ago`,
  timeHAgo: (h: number) => `${h}h ago`,
  timeDayAgo: (d: number) => `${d}d ago`,

  dashTitle: "Dashboard",
  dashSubtitle: "Welcome back, Admin",
  dashEnDesarrollo: "In development",
  dashCancelados: "Cancelled",
  dashShortcuts: "Quick access",
  dashPedidosMes: "Orders per month",
  dashPedidosEstado: "Orders by status",
  dashPedidosActivos: "Active Orders",
  dashNoPedidosActivos: "No active orders",
  dashPedidosPlazo: "Orders with Deadline",
  dashNoPedidosPlazo: "No orders with deadline",
  dashProyecto: "Project",
  dashCliente: "Client",
  dashEstado: "Status",
  dashPlazo: "Deadline",
  dashVencido: "Overdue",
  dashHoy: "Today",
  dashPendiente: "Pending",
  dashDesarrollo: "In development",
  dashRevision: "In review",
  dashEntregado: "Delivered",

  clientesTitle: "Clients",
  clientesSubtitle: "Register new client",
  clientesConfirmTitle: "Save client?",
  clientesConfirmMsg: "The new client will be registered in the system. Do you want to continue?",
  clientesConfirmBtn: "Yes, save",
  clientesDatosPersonales: "PERSONAL DATA",
  clientesNombreCompleto: "Full name",
  clientesDni: "ID / Passport",
  clientesCorreo: "Email address",
  clientesTelefono: "Phone number",
  clientesPais: "Country",
  clientesSelPais: "Select country",
  clientesAppWeb: "App / Website name",
  clientesFechasContrato: "DATES & CONTRACT",
  clientesFechaInicio: "Start date",
  clientesSelFechaInicio: "Select start date",
  clientesFechaMaxima: "Maximum delivery date",
  clientesSelFechaMaxima: "Select maximum date",
  clientesDuracion: "Contract duration",
  clientesSelDuracion: "Select duration",
  clientesSinContrato: "No contract",
  clientesTipoPago: "Payment type",
  clientesSelTipoPago: "Select payment type",
  clientesPagoMensual: "Monthly payments",
  clientesPagoUnico: "One-time payment",
  clientesValorMensual: "Monthly value (USD)",
  clientesValorTotal: "Total value (USD)",
  clientesAcceso: "SYSTEM ACCESS",
  clientesPassword: "Password",
  clientesCrearPasswordPH: "Create password",
  clientesConfirmarPassword: "Confirm password",
  clientesRepetirPasswordPH: "Repeat password",
  clientesPasswordNoCoinciden: "Passwords do not match",
  clientesGuardar: "Save client",
  clientesRegistrados: "Registered clients",
  clientesBuscar: "Search by name, email, country...",
  clientesContrato: "Contract",
  clientesValor: "Value",
  clientesInicio: "Start",
  clientesCargando: "Loading...",
  clientesSinResultados: "No results",
  clientesEjNombre: "e.g. John Smith",
  clientesEjDni: "e.g. 12345678",
  clientesEjTelefono: "+1 999 999 9999",
  clientesEjAppWeb: "e.g. MyStore Online",
  clientesEjValorMensual: "e.g. 150.00",
  clientesEjValorTotal: "e.g. 1200.00",
  clientesCampoObligatorio: "Required field",
  clientesSelPaisError: "Select a country",
  clientesSelFechaError: "Select a date",
  clientesSelDuracionError: "Select a duration",
  clientesSelPagoError: "Select payment type",
  clientesCrearPasswordError: "Create a password",
  clientesGuardadoOk: "Client saved successfully",
  clientesGuardadoError: "Error saving client",
  clientesMes: "month",
  clientesMeses: "months",
  clientesXMes: "/mo",
  clientesSingular: "client",
  clientesPlural: "clients",

  pedidosTitle: "Orders",
  pedidosSubtitleNuevo: "Register new order",
  pedidosSubtitleEditar: "Editing existing order",
  pedidosCancelarEdicion: "Cancel editing",
  pedidosConfirmTitleNuevo: "Save order?",
  pedidosConfirmTitleEditar: "Save changes?",
  pedidosConfirmMsgNuevo: "The new order will be registered in the system. Do you want to continue?",
  pedidosConfirmMsgEditar: "The order data will be updated. Do you want to continue?",
  pedidosConfirmBtn: "Yes, save",
  pedidosDatos: "ORDER DETAILS",
  pedidosCliente: "Client",
  pedidosSelCliente: "Select client",
  pedidosNombreProyecto: "Project name",
  pedidosEjProyecto: "e.g. MyStore Online",
  pedidosTipoProyecto: "Project type",
  pedidosSelTipo: "Select type",
  pedidosTipoServicio: "Service type",
  pedidosSelServicio: "Select service",
  pedidosPrioridad: "Priority",
  pedidosSelPrioridad: "Select priority",
  pedidosEstadoLabel: "Order status",
  pedidosSelEstado: "Select status",
  pedidosFechaInicio: "Start date",
  pedidosSelFechaInicio: "Select start date",
  pedidosFechaEntrega: "Delivery date",
  pedidosSelFechaEntrega: "Select delivery date",
  pedidosPlataformas: "PLATFORMS / TECHNOLOGIES",
  pedidosSelTecnologias: "Select project technologies",
  pedidosMensajeInicio: "INITIAL MESSAGE",
  pedidosMensajeLabel: "Project initial message",
  pedidosMensajePH: "e.g. Hi Carlos, we start today with the development of your project...",
  pedidosGuardar: "Save order",
  pedidosGuardarCambios: "Save changes",
  pedidosCancelar: "Cancel",
  pedidosRegistrados: "Registered orders",
  pedidosBuscar: "Search by project, client...",
  pedidosServicio: "Service",
  pedidosEntrega: "Delivery",
  pedidosSinResultados: "No results",
  pedidosActualizadoOk: "Order updated successfully",
  pedidosGuardadoOk: "Order saved successfully",
  pedidosGuardadoError: "Error saving order",
  pedidosSelClienteError: "Select a client",
  pedidosNombreError: "Enter the project name",
  pedidosTipoError: "Select the project type",
  pedidosServicioError: "Select the service type",
  pedidosPrioridadError: "Select the priority",
  pedidosEstadoError: "Select the status",
  pedidosFechaInicioError: "Enter the start date",
  pedidosFechaEntregaError: "Enter the delivery date",
  pedidosMensajeError: "Write an initial message",
  pedidosCargando: "Loading...",
  pedidosSingular: "order",
  pedidosPlural: "orders",
  pedidosPagoInfo: "PAYMENT INFORMATION",
  pedidosMontoTotal: "Total project amount (USD)",
  pedidosMontoTotalPH: "e.g. 1200.00",
  pedidosMontoPagado: "Amount paid (USD)",
  pedidosMontoPagadoPH: "e.g. 600.00",
  pedidosMontoPendiente: "Pending amount",
  pedidosSubirComprobante: "Upload receipt (image or PDF)",
  pedidosComprobanteActual: "Current receipt",
  pedidosVerComprobante: "View receipt",
  pedidosComprobanteSubiendo: "Uploading...",
  pedidosComprobanteError: "Error uploading receipt",
  pedidosComprobanteOk: "Receipt uploaded successfully",
  tipoWeb: "Website / Web App",
  tipoApp: "Mobile App",
  tipoDesktop: "Desktop App",
  prioBaja: "Low",
  prioMedia: "Medium",
  prioAlta: "High",
  prioUrgente: "Urgent",
  estadoPendiente: "Pending",
  estadoDesarrollo: "In development",
  estadoRevision: "In review",
  estadoEntregado: "Delivered",
  estadoCancelado: "Cancelled",
  badgeWeb: "Web",
  badgeApp: "Mobile App",
  badgeDesktop: "Desktop",
  srvLanding: "Landing Page",
  srvEcommerce: "E-Commerce / Online Store",
  srvAuth: "Authentication System",
  srvApi: "REST API / Backend",
  srvDashboard: "Dashboard / Admin Panel",
  srvBlog: "Blog / News Portal",
  srvPortfolio: "Portfolio / Brochure",
  srvCrm: "CRM / Client Management",
  srvErp: "ERP / Business Management",
  srvPos: "Point of Sale (POS)",
  srvBooking: "Bookings / Online Appointments",
  srvChat: "Chat / Real-time Messaging",
  srvStreaming: "Streaming / Video On Demand",
  srvMarketplace: "Marketplace",
  srvSaas: "SaaS / Software as a Service",
  srvSocial: "Social Network / Community",
  srvMaps: "Maps / Geolocation",
  srvNotif: "Push Notifications",
  srvPayments: "Payment Gateway",
  srvIa: "AI Integration / Chatbot",
  srvScraping: "Web Scraping / Automation",
  srvOther: "Other / Custom",

  pagosTitle: "Payments",
  pagosSubtitle: "Payment record per order",
  pagosCargando: "Loading payments...",
  pagosNinguno: "No registered orders",
  pagosMontoTotal: "Total",
  pagosMontoPagado: "Paid",
  pagosMontoPendiente: "Pending",
  pagosComprobante: "Receipt",
  pagosVerComprobante: "View",
  pagosSinComprobante: "—",
  pagosResumenFacturado: "Total billed",
  pagosResumenPagado: "Total paid",
  pagosResumenPendiente: "Total pending",
  pagosResumenPedidos: "Orders with payment",
  pagosSaldado: "Paid off",
  pagosDeuda: "Outstanding",
  pagosSinInfo: "No info",
  pagosEstadoPago: "Payment status",
  pagosBuscar: "Search by project, client...",
  pagosSingular: "order",
  pagosPlural: "orders",

  mensajesTitle: "Messages",
  mensajesBuscar: "Search client...",
  mensajesSinResultados: "No results",
  mensajesNoHay: "No clients",
  mensajesSinMensajes: "No messages",
  mensajesSelecciona: "Select a client to view the conversation",
  mensajesVacio: "No messages yet. Write the first one!",
  mensajesEscribe: "Write a message...",
  mensajesExpandir: "Expand",
  mensajesColapsar: "Collapse",

  proyectosTitle: "Completed Projects",
  proyectosNinguno: "No completed projects yet",
  proyectosCargando: "Loading completed projects...",
  proyectosSingular: "project",
  proyectosPlural: "projects",
  proyectosTermSingular: "completed",
  proyectosTermPlural: "completed",
  proyectosMensajeFinalLabel: "Final message for the client",
  proyectosGuardarMensaje: "Save message",
  proyectosCerrar: "Close",
  proyectosEditarMensaje: "Edit message",
  proyectosMensajeFinalBtn: "Final message",
  proyectosGuardadoOk: "Message saved successfully",
  proyectosGuardadoError: "Error saving message",

  canceladosTitle: "Cancelled Projects",
  canceladosNinguno: "No cancelled projects",
  canceladosCargando: "Loading cancelled projects...",
  canceladosSingular: "project",
  canceladosPlural: "projects",
  canceladosCancelSingular: "cancelled",
  canceladosCancelPlural: "cancelled",
  canceladosMotivoLabel: "Cancellation reason",
  canceladosMotivoPH: "Describe the reason why the project was cancelled...",
  canceladosGuardarMotivo: "Save reason",
  canceladosCerrar: "Close",
  canceladosEditarMotivo: "Edit reason",
  canceladosMotivoBtn: "Reason",
  canceladosGuardadoOk: "Reason saved successfully",
  canceladosGuardadoError: "Error saving reason",
  canceladosInicioLabel: "Start",
  canceladosCanceladoLabel: "Cancelled",

  fechaEntregaTitle: "Delivery Dates",
  fechaEntregaSubtitle: "Projects sorted by maximum deadline",
  fechaEntregaCargando: "Loading delivery dates...",
  fechaEntregaNoPedidos: "No registered orders",
  fechaEntregaVencidoHace: "Overdue by",
  fechaEntregaVenceHoy: "Due today",
  fechaEntregaEntregado: "Delivered",
  fechaEntregaVencidosSing: "overdue",
  fechaEntregaVencidosPlu: "overdue",
  fechaEntregaUrgentesSing: "urgent",
  fechaEntregaUrgentesPlu: "urgent",
  fechaEntregaTresDias: "(≤ 3 days)",
  fechaEntregaEntregadosSing: "delivered",
  fechaEntregaEntregadosPlu: "delivered",
  diaSingular: "day",
  diasPlural: "days",

  fechaInicioTitle: "Start Dates",
  fechaInicioSubtitle: "Project history by start date",
  fechaInicioCargando: "Loading start dates...",
  fechaInicioNoPedidos: "No registered orders",

  alertasTitle: "Alerts",
  alertasTodoOk: "All clear — no active alerts",
  alertasCargando: "Analyzing alerts...",
  alertasSinPendientes: "No pending",
  alertasVencidas: "Overdue deliveries",
  alertasHoy: "Due today",
  alertasProximas: "Upcoming deliveries (≤ 7 days)",
  alertasUrgentes: "Urgent orders in progress",
  alertasPendientes: "Pending orders",
  alertasCancelados: "Cancelled projects",
  alertasVencioEl: "Expired on",
  alertasEstadoLabel: "Status",
  alertasEnDias: (d: number) => `In ${d} day${d !== 1 ? "s" : ""}`,
  alertasPrioridadLabel: "Priority",
  alertasCanceladoEl: "Cancelled on",
  alertasSingular: "alert",
  alertasPlural: "alerts",
  alertasActivaSingular: "active",
  alertasActivaPlural: "active",

  configTitle: "Settings",
  configSubtitle: "Administrator and system settings",
  configCargando: "Loading settings...",
  configCambiarFoto: "Change photo",
  configPerfil: "ADMINISTRATOR PROFILE",
  configNombre: "Name",
  configNombrePH: "Admin name",
  configCorreo: "Email address",
  configTelefono: "Phone",
  configEmpresa: "COMPANY DATA",
  configNombreEmpresa: "Company name",
  configNombreEmpresaPH: "My Company",
  configSitio: "Website",
  configSitioPH: "mycompany.com",
  configCV: "CURRICULUM VITAE",
  configDescargar: "Download",
  configSubirCV: "Upload CV (PDF, DOC)",
  configSubiendo: "Uploading...",
  configImagenError: "Image must not exceed 500 KB",
  configArchivoError: "File must not exceed 10 MB",
  configCVSubidoOk: "CV uploaded successfully",
  configCVSubidoError: "Error uploading CV",
  configCVEliminadoOk: "CV deleted",
  configCVEliminadoError: "Error deleting CV",
  configGuardadoOk: "Settings saved successfully",
  configGuardadoError: "Error saving",
  configGuardar: "Save settings",
  configGuardando: "Saving...",

  reporteTitle: "Technical Report",
  reporteSubtitle: "General system summary",
  reporteExportar: "Export / Print",
  reporteTotalClientes: "Total clients",
  reporteTotalPedidos: "Total orders",
  reporteConcluidos: "Completed projects",
  reporteCancelados: "Cancelled projects",
  reporteEnDesarrollo: "In development / review",
  reporteIngresos: "Estimated revenue",
  reporteResumen: "Summary",
  reportePedidos: "Orders",
  reporteClientes: "Clients",
  reporteGenerando: "Generating report...",
  reporteNoPedidos: "No registered orders",
  reporteNoClientes: "No registered clients",
  reporteProyecto: "Project",
  reporteServicio: "Service",
  reporteInicio: "Start",
  reporteEntrega: "Delivery",
  reporteEstado: "Status",
  reportePrioridad: "Priority",
  reporteTipo: "Type",
  reporteTecnologias: "Technologies",
  reporteCorreo: "Email",
  reportePais: "Country",
  reporteContrato: "Contract",
  reportePago: "Payment",
  reporteValor: "Value",
  reporteMes: "month",
  reporteMeses: "months",
  reporteMensual: "Monthly",
  reporteUnico: "One-time",
  reporteConcluidosSeccion: "Completed Projects —",
  reporteNoProyectosConcluidos: "No completed projects",
  reporteMensajeFinal: "Final message",
  reporteSinMensaje: "No message",

  pwTitle: "Change password",
  pwSubtitle: "Enter your current password and the new one",
  pwActual: "Current password",
  pwActualPH: "Your current password",
  pwNueva: "New password",
  pwNuevaPH: "New password",
  pwConfirmar: "Confirm new password",
  pwConfirmarPH: "Repeat new password",
  pwNoCoinciden: "Passwords do not match",
  pwCancelar: "Cancel",
  pwCambiar: "Change password",
  pwGuardando: "Saving...",
  pwErrorActualReq: "Enter your current password.",
  pwErrorMinChars: "New password must be at least 6 characters.",
  pwErrorNoCoinciden: "New passwords do not match.",
  pwErrorActualWrong: "Current password is incorrect.",
  pwErrorGeneral: "An error occurred. Please try again.",
  pwActualizadaOk: "Password updated successfully",

  loading: "Loading...",
  saving: "Saving...",
  noResults: "No results",
};

export type TKey = keyof typeof ES;
export type T = typeof ES;

const translations: Record<Lang, T> = { ES, EN };

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: T;
}

const LangContext = createContext<LangContextType>({
  lang: "ES",
  setLang: () => {},
  t: ES,
});

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>("ES");
  return (
    <LangContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
